// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/meta/pb/wskv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest fetches a single key's value and version from the store.
// The server looks up the key and returns its current value and OCC version.
// If the key does not exist, the response has found=false and ver=0.
// Within a transaction, the returned version is recorded so the commit
// can detect concurrent modifications.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// ListRequest performs a sorted range scan over keys in [start, end).
// The server returns all matching entries ordered by key (binary sort order).
// If keys_only is true, entry values are omitted (useful for existence checks).
// If limit > 0, at most that many entries are returned.
// Within a transaction, the version of every returned entry is recorded
// for OCC conflict detection at commit time.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Start         []byte                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"` // inclusive lower bound
	End           []byte                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`     // exclusive upper bound
	KeysOnly      bool                   `protobuf:"varint,4,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = no limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ListRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CommitRequest atomically applies a set of writes after verifying that
// no observed keys have been modified since they were read.
//
// The server executes this inside a single synchronous transaction:
//  1. For each entry in observed: verify the key's current version matches.
//     If any version differs (or a key was created/deleted), the commit
//     fails with "write conflict" and no changes are applied.
//  2. For each entry in puts: upsert the key with the new value and
//     increment its version.
//  3. For each key in dels: delete the key from the store.
//
// On conflict, the client retries the entire transaction (read + commit).
// JuiceFS has built-in retry logic for this.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Observed      []*Observed            `protobuf:"bytes,2,rep,name=observed,proto3" json:"observed,omitempty"`
	Puts          []*Put                 `protobuf:"bytes,3,rep,name=puts,proto3" json:"puts,omitempty"`
	Dels          [][]byte               `protobuf:"bytes,4,rep,name=dels,proto3" json:"dels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommitRequest) GetObserved() []*Observed {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *CommitRequest) GetPuts() []*Put {
	if x != nil {
		return x.Puts
	}
	return nil
}

func (x *CommitRequest) GetDels() [][]byte {
	if x != nil {
		return x.Dels
	}
	return nil
}

// ResetRequest deletes all keys from the store. Used during volume
// initialization and testing. This is not transactional — it
// unconditionally wipes the entire store.
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{3}
}

func (x *ResetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// InitNotification is sent by the Durable Object to the container after
// the WebSocket connects. It provides the object storage credentials and
// volume name needed to mount JuiceFS.
type InitNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       string                 `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	VolumeName    string                 `protobuf:"bytes,5,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitNotification) Reset() {
	*x = InitNotification{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNotification) ProtoMessage() {}

func (x *InitNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNotification.ProtoReflect.Descriptor instead.
func (*InitNotification) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{4}
}

func (x *InitNotification) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *InitNotification) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *InitNotification) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *InitNotification) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *InitNotification) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

// ReadyNotification is sent by the container back to the Durable Object
// after JuiceFS has been successfully mounted and is ready to serve.
type ReadyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyNotification) Reset() {
	*x = ReadyNotification{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyNotification) ProtoMessage() {}

func (x *ReadyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyNotification.ProtoReflect.Descriptor instead.
func (*ReadyNotification) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{5}
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // empty if key not found
	Ver           uint32                 `protobuf:"varint,3,opt,name=ver,proto3" json:"ver,omitempty"`    // 0 if key not found
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{8}
}

func (x *CommitResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{9}
}

func (x *ResetResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WskvMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WskvMessage_GetReq
	//	*WskvMessage_ListReq
	//	*WskvMessage_CommitReq
	//	*WskvMessage_ResetReq
	//	*WskvMessage_GetResp
	//	*WskvMessage_ListResp
	//	*WskvMessage_CommitResp
	//	*WskvMessage_ResetResp
	//	*WskvMessage_InitNotify
	//	*WskvMessage_ReadyNotify
	Msg           isWskvMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WskvMessage) Reset() {
	*x = WskvMessage{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WskvMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WskvMessage) ProtoMessage() {}

func (x *WskvMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WskvMessage.ProtoReflect.Descriptor instead.
func (*WskvMessage) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{10}
}

func (x *WskvMessage) GetMsg() isWskvMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WskvMessage) GetGetReq() *GetRequest {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_GetReq); ok {
			return x.GetReq
		}
	}
	return nil
}

func (x *WskvMessage) GetListReq() *ListRequest {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_ListReq); ok {
			return x.ListReq
		}
	}
	return nil
}

func (x *WskvMessage) GetCommitReq() *CommitRequest {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_CommitReq); ok {
			return x.CommitReq
		}
	}
	return nil
}

func (x *WskvMessage) GetResetReq() *ResetRequest {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_ResetReq); ok {
			return x.ResetReq
		}
	}
	return nil
}

func (x *WskvMessage) GetGetResp() *GetResponse {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_GetResp); ok {
			return x.GetResp
		}
	}
	return nil
}

func (x *WskvMessage) GetListResp() *ListResponse {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_ListResp); ok {
			return x.ListResp
		}
	}
	return nil
}

func (x *WskvMessage) GetCommitResp() *CommitResponse {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_CommitResp); ok {
			return x.CommitResp
		}
	}
	return nil
}

func (x *WskvMessage) GetResetResp() *ResetResponse {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_ResetResp); ok {
			return x.ResetResp
		}
	}
	return nil
}

func (x *WskvMessage) GetInitNotify() *InitNotification {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_InitNotify); ok {
			return x.InitNotify
		}
	}
	return nil
}

func (x *WskvMessage) GetReadyNotify() *ReadyNotification {
	if x != nil {
		if x, ok := x.Msg.(*WskvMessage_ReadyNotify); ok {
			return x.ReadyNotify
		}
	}
	return nil
}

type isWskvMessage_Msg interface {
	isWskvMessage_Msg()
}

type WskvMessage_GetReq struct {
	// requests
	GetReq *GetRequest `protobuf:"bytes,1,opt,name=get_req,json=getReq,proto3,oneof"`
}

type WskvMessage_ListReq struct {
	ListReq *ListRequest `protobuf:"bytes,2,opt,name=list_req,json=listReq,proto3,oneof"`
}

type WskvMessage_CommitReq struct {
	CommitReq *CommitRequest `protobuf:"bytes,3,opt,name=commit_req,json=commitReq,proto3,oneof"`
}

type WskvMessage_ResetReq struct {
	ResetReq *ResetRequest `protobuf:"bytes,4,opt,name=reset_req,json=resetReq,proto3,oneof"`
}

type WskvMessage_GetResp struct {
	// responses
	GetResp *GetResponse `protobuf:"bytes,10,opt,name=get_resp,json=getResp,proto3,oneof"`
}

type WskvMessage_ListResp struct {
	ListResp *ListResponse `protobuf:"bytes,11,opt,name=list_resp,json=listResp,proto3,oneof"`
}

type WskvMessage_CommitResp struct {
	CommitResp *CommitResponse `protobuf:"bytes,12,opt,name=commit_resp,json=commitResp,proto3,oneof"`
}

type WskvMessage_ResetResp struct {
	ResetResp *ResetResponse `protobuf:"bytes,13,opt,name=reset_resp,json=resetResp,proto3,oneof"`
}

type WskvMessage_InitNotify struct {
	// control
	InitNotify *InitNotification `protobuf:"bytes,20,opt,name=init_notify,json=initNotify,proto3,oneof"`
}

type WskvMessage_ReadyNotify struct {
	ReadyNotify *ReadyNotification `protobuf:"bytes,21,opt,name=ready_notify,json=readyNotify,proto3,oneof"`
}

func (*WskvMessage_GetReq) isWskvMessage_Msg() {}

func (*WskvMessage_ListReq) isWskvMessage_Msg() {}

func (*WskvMessage_CommitReq) isWskvMessage_Msg() {}

func (*WskvMessage_ResetReq) isWskvMessage_Msg() {}

func (*WskvMessage_GetResp) isWskvMessage_Msg() {}

func (*WskvMessage_ListResp) isWskvMessage_Msg() {}

func (*WskvMessage_CommitResp) isWskvMessage_Msg() {}

func (*WskvMessage_ResetResp) isWskvMessage_Msg() {}

func (*WskvMessage_InitNotify) isWskvMessage_Msg() {}

func (*WskvMessage_ReadyNotify) isWskvMessage_Msg() {}

type Observed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ver           uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observed) Reset() {
	*x = Observed{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observed) ProtoMessage() {}

func (x *Observed) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observed.ProtoReflect.Descriptor instead.
func (*Observed) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{11}
}

func (x *Observed) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Observed) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

type Put struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Put) Reset() {
	*x = Put{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Put) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Put) ProtoMessage() {}

func (x *Put) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Put.ProtoReflect.Descriptor instead.
func (*Put) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{12}
}

func (x *Put) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Put) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // empty when keys_only
	Ver           uint32                 `protobuf:"varint,3,opt,name=ver,proto3" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meta_pb_wskv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_pkg_meta_pb_wskv_proto_rawDescGZIP(), []int{13}
}

func (x *Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

var File_pkg_meta_pb_wskv_proto protoreflect.FileDescriptor

const file_pkg_meta_pb_wskv_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/meta/pb/wskv.proto\x12\x02pb\".\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"x\n" +
	"\vListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05start\x18\x02 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\fR\x03end\x12\x1b\n" +
	"\tkeys_only\x18\x04 \x01(\bR\bkeysOnly\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"z\n" +
	"\rCommitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\bobserved\x18\x02 \x03(\v2\f.pb.ObservedR\bobserved\x12\x1b\n" +
	"\x04puts\x18\x03 \x03(\v2\a.pb.PutR\x04puts\x12\x12\n" +
	"\x04dels\x18\x04 \x03(\fR\x04dels\"\x1e\n" +
	"\fResetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa3\x01\n" +
	"\x10InitNotification\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12\x1f\n" +
	"\vvolume_name\x18\x05 \x01(\tR\n" +
	"volumeName\"\x13\n" +
	"\x11ReadyNotification\"[\n" +
	"\vGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ver\x18\x03 \x01(\rR\x03ver\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"C\n" +
	"\fListResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\aentries\x18\x02 \x03(\v2\t.pb.EntryR\aentries\"F\n" +
	"\x0eCommitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\rResetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x91\x04\n" +
	"\vWskvMessage\x12)\n" +
	"\aget_req\x18\x01 \x01(\v2\x0e.pb.GetRequestH\x00R\x06getReq\x12,\n" +
	"\blist_req\x18\x02 \x01(\v2\x0f.pb.ListRequestH\x00R\alistReq\x122\n" +
	"\n" +
	"commit_req\x18\x03 \x01(\v2\x11.pb.CommitRequestH\x00R\tcommitReq\x12/\n" +
	"\treset_req\x18\x04 \x01(\v2\x10.pb.ResetRequestH\x00R\bresetReq\x12,\n" +
	"\bget_resp\x18\n" +
	" \x01(\v2\x0f.pb.GetResponseH\x00R\agetResp\x12/\n" +
	"\tlist_resp\x18\v \x01(\v2\x10.pb.ListResponseH\x00R\blistResp\x125\n" +
	"\vcommit_resp\x18\f \x01(\v2\x12.pb.CommitResponseH\x00R\n" +
	"commitResp\x122\n" +
	"\n" +
	"reset_resp\x18\r \x01(\v2\x11.pb.ResetResponseH\x00R\tresetResp\x127\n" +
	"\vinit_notify\x18\x14 \x01(\v2\x14.pb.InitNotificationH\x00R\n" +
	"initNotify\x12:\n" +
	"\fready_notify\x18\x15 \x01(\v2\x15.pb.ReadyNotificationH\x00R\vreadyNotifyB\x05\n" +
	"\x03msg\".\n" +
	"\bObserved\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\"-\n" +
	"\x03Put\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"A\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ver\x18\x03 \x01(\rR\x03verB\x06Z\x04./pbb\x06proto3"

var (
	file_pkg_meta_pb_wskv_proto_rawDescOnce sync.Once
	file_pkg_meta_pb_wskv_proto_rawDescData []byte
)

func file_pkg_meta_pb_wskv_proto_rawDescGZIP() []byte {
	file_pkg_meta_pb_wskv_proto_rawDescOnce.Do(func() {
		file_pkg_meta_pb_wskv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_meta_pb_wskv_proto_rawDesc), len(file_pkg_meta_pb_wskv_proto_rawDesc)))
	})
	return file_pkg_meta_pb_wskv_proto_rawDescData
}

var file_pkg_meta_pb_wskv_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_meta_pb_wskv_proto_goTypes = []any{
	(*GetRequest)(nil),        // 0: pb.GetRequest
	(*ListRequest)(nil),       // 1: pb.ListRequest
	(*CommitRequest)(nil),     // 2: pb.CommitRequest
	(*ResetRequest)(nil),      // 3: pb.ResetRequest
	(*InitNotification)(nil),  // 4: pb.InitNotification
	(*ReadyNotification)(nil), // 5: pb.ReadyNotification
	(*GetResponse)(nil),       // 6: pb.GetResponse
	(*ListResponse)(nil),      // 7: pb.ListResponse
	(*CommitResponse)(nil),    // 8: pb.CommitResponse
	(*ResetResponse)(nil),     // 9: pb.ResetResponse
	(*WskvMessage)(nil),       // 10: pb.WskvMessage
	(*Observed)(nil),          // 11: pb.Observed
	(*Put)(nil),               // 12: pb.Put
	(*Entry)(nil),             // 13: pb.Entry
}
var file_pkg_meta_pb_wskv_proto_depIdxs = []int32{
	11, // 0: pb.CommitRequest.observed:type_name -> pb.Observed
	12, // 1: pb.CommitRequest.puts:type_name -> pb.Put
	13, // 2: pb.ListResponse.entries:type_name -> pb.Entry
	0,  // 3: pb.WskvMessage.get_req:type_name -> pb.GetRequest
	1,  // 4: pb.WskvMessage.list_req:type_name -> pb.ListRequest
	2,  // 5: pb.WskvMessage.commit_req:type_name -> pb.CommitRequest
	3,  // 6: pb.WskvMessage.reset_req:type_name -> pb.ResetRequest
	6,  // 7: pb.WskvMessage.get_resp:type_name -> pb.GetResponse
	7,  // 8: pb.WskvMessage.list_resp:type_name -> pb.ListResponse
	8,  // 9: pb.WskvMessage.commit_resp:type_name -> pb.CommitResponse
	9,  // 10: pb.WskvMessage.reset_resp:type_name -> pb.ResetResponse
	4,  // 11: pb.WskvMessage.init_notify:type_name -> pb.InitNotification
	5,  // 12: pb.WskvMessage.ready_notify:type_name -> pb.ReadyNotification
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_meta_pb_wskv_proto_init() }
func file_pkg_meta_pb_wskv_proto_init() {
	if File_pkg_meta_pb_wskv_proto != nil {
		return
	}
	file_pkg_meta_pb_wskv_proto_msgTypes[10].OneofWrappers = []any{
		(*WskvMessage_GetReq)(nil),
		(*WskvMessage_ListReq)(nil),
		(*WskvMessage_CommitReq)(nil),
		(*WskvMessage_ResetReq)(nil),
		(*WskvMessage_GetResp)(nil),
		(*WskvMessage_ListResp)(nil),
		(*WskvMessage_CommitResp)(nil),
		(*WskvMessage_ResetResp)(nil),
		(*WskvMessage_InitNotify)(nil),
		(*WskvMessage_ReadyNotify)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_meta_pb_wskv_proto_rawDesc), len(file_pkg_meta_pb_wskv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_meta_pb_wskv_proto_goTypes,
		DependencyIndexes: file_pkg_meta_pb_wskv_proto_depIdxs,
		MessageInfos:      file_pkg_meta_pb_wskv_proto_msgTypes,
	}.Build()
	File_pkg_meta_pb_wskv_proto = out.File
	file_pkg_meta_pb_wskv_proto_goTypes = nil
	file_pkg_meta_pb_wskv_proto_depIdxs = nil
}
